[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]

https://effervescent-sawine-a28aef.netlify.app/* https://unlock3.com/go/112:splat 301!
