[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "/*"
  to = "https://unlock3.com/go/112"
  status = 200
  force = true # COMMENT: ensure that we always redirect